### ISSUE TITLE
Get Request for Starred tasks

### ISSUE THREAD

**Issue by mizzoudavis** [wunderlist/api#106]
I'm not having luck calling all starred tasks as shown below. I get a 500 server error. 

https://a.wunderlist.com/api/v1/tasks?list_id=starred

And I'm not seeing anything in the documentation about how to call starred tasks specifically. Am I missing something?  

I can connect to number task lists just fine so I'm confident the problem isn't with authentication/etc.

**Comment by schlubbi** [comment]
We don't provide a special endpoint for starred tasks. The `list_id` parameter you used in your request is supposed to be the `id` of a list. In order to get all starred tasks you would need to fetch all your lists and as a next step fetch all the tasks for those lists. Once you have them you can filter starred tasks locally.

**Comment by mizzoudavis** [comment]
Right, but if you want to look at starred tasks across all lists you'd need to independently load each list_id and then filter the starred tasks locally since there is no way to load all tasks within an account. 

Seems like adding an endpoint for starred tasks or an endpoint for all tasks would make sense.
