### ISSUE TITLE
API via PHP

### ISSUE THREAD

**Issue by wfabian** [wunderlist/api#55]
Hi,
i'm tryin to access the Wunderlist-API via PHP.
I modify an existing PHP-Class: https://github.com/jeroendesloovere/wunderlist-php-api

I do an Authenticate-Call via PHP/Curl and i'm gettin a access-token.
But when i try to get my lists, i'm just gettin an error for https://a.wunderlist.com/api/v1/lists : 
_{"error":{"type":"server_error","translation_key":"api_error_unknown","message":"An unknown server error occurred","authentication":["missing"]}}
_

I set the accees-token and the Client-ID in the header.

Is there any PHP-Api which i can use instead? 
Or is the anyone, who can help?
Would be awesome - Thank You!

**Comment by ericyahhh** [comment]
Hi Fabian,

The PHP API wrapper you're referring to seems to be outdated. It's wrapping our old API, which has been shut down a while ago.

From the separate email you sent us I could also see that you're setting the header for Client ID incorrectly: `X-Access-Client-ID` instead of `X-Client-ID`.

Eric

**Comment by wfabian** [comment]
Hi Eric,
thanks for your answer.

I implent the API myself. The referred API-Wrapper is just my base. I will update it to the latest API.

> From the separate email you sent us I could also see that you're setting the header for Client ID incorrectly: X-Access-Client-ID instead of X-Client-ID.

That solved my problem!
