### ISSUE TITLE
Create Task not working ??

### ISSUE THREAD

**Issue by mehulsbhandari** [wunderlist/api#65]
curl -X POST -H "Content-Type:application/json" -H "processData:false" -H "X-Access-Token: XXXXX" -H "X-Client-ID: XXXXXXXXX" https://a.wunderlist.com/api/v... -d '{"list_id":"12345","title":"Mehul Wunderlist API","assignee_id":"5515","completed":"true","due_date":"2016-05-15","starred":"false"}'

Not Working . What i have done wrong ??

{"error":{"type":"missing_parameter","translation_key":"api_error_missing_params","message":"Missing parameter.","completed":["required"]}}

**Comment by idpaterson** [comment]
It looks like all of your property values are represented as strings. The Wunderlist API expects numbers and booleans rather than strings for some of the values you have specified here. Try the following instead. If you are converting to JSON from another data format be sure to use the proper data type rather than strings.

```json
{"list_id":12345,"title":"Mehul Wunderlist API","assignee_id":5515,"completed":true,"due_date":"2016-05-15","starred":false}
```

**Comment by mehulsbhandari** [comment]
Great ... you solve my query ...
