### ISSUE TITLE
updated_at timestamp on Task object

### ISSUE THREAD

**Issue by hyfen** [wunderlist/api#89]
It would be great to have an updated_at property on a Task in addition to the revision property. Is there any reason it's not returned right now?

**Comment by schlubbi** [comment]
I don't recall if we had any specific reasoning for not exposing that field. Our own clients down require it in order to sync data, because they only need the revision of an object. There are currently no plans to expose `updated_at` on any object in our API. I will put it on our list of future improvements tho. For the sake of consistency that update would need to be introduced to all endpoints in the API. 

Sorry for the late response and thanks for the suggestion!
